// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJgiRjDOsIRMDTPU13fZ0xO-1dtu1lOw',
    appId: '1:236818307899:android:702eab559c3a2839d3351e',
    messagingSenderId: '236818307899',
    projectId: 'hospital2-221f5',
    storageBucket: 'hospital2-221f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PBa7YwZK8gffo4nqGR6wlkyzrnZteDo',
    appId: '1:236818307899:ios:bfb81028abeb3b09d3351e',
    messagingSenderId: '236818307899',
    projectId: 'hospital2-221f5',
    storageBucket: 'hospital2-221f5.appspot.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLfgdCmVAy1wE6hcbBKatyx11VJ2xtq0',
    appId: '1:236818307899:web:ed6e1f4791e5e285d3351e',
    messagingSenderId: '236818307899',
    projectId: 'hospital2-221f5',
    authDomain: 'hospital2-221f5.firebaseapp.com',
    storageBucket: 'hospital2-221f5.appspot.com',
    measurementId: 'G-DZWPYCNBDK',
  );

}